name: ResourceControlPlugin
version: '${version}'

main: net.dvmn2.resourcecontrolplugin.ResourceControlPlugin
api-version: '1.21'
load: POSTWORLD

authors: [ DVMN2 ]

permissions:
  resourcecontrol.admin:
    description: Доступ к командам /resourcecontrol
    default: op
  resourcecontrol.bypass:
    description: Не кикается за отсутствие клиентского мода ResourceControl
    default: false
